name:               "MIMI"
description:        "mimi的博客"

url:                "http://b34.photo.store.qq.com/psu?/c53a2025-9359-4fb0-b836-2df34e714eff/c4JlP4DMzJiIBp9ew.kXiqtgcN8ShCQR7GeTyANIsyw!/b/YYyvJBb6XwAAYsgmTRSPpQAA&a=37&b=34&bo=8ABAAQAAAAABBJI!&rf=viewer_4"
author:             "mimi"
email:              "754199572@qq.com"
gravatar_hash:      "205e460b479e2e5b48aec07710c08d50"
#twitter:            "jhondoe"
#email:              "jhondoe@abc.com"
github:             "yandeguangzy"
#pinterest:          "jhondoe"
#linkedin:           "jhondoe"
#facebook:           "jhondoe"

disqus_shortname:   "thinker3197"

background:         "https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1548251196602&di=562a04825252154d2431c2a470701c53&imgtype=0&src=http%3A%2F%2Fpic16.photophoto.cn%2F20100921%2F0008020224500580_b.jpg"

paginate:           5
paginate_path:      "/page:num/"

baseurl:            ""
permalink:          /:year/:month/:day/:title/

markdown:           kramdown

nav:
  - name:           "About"
    href:           "/about"
  - name:           "Download"
    href:           "/releases"

sass:
  style:            :compressed

defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

gems:
  - jekyll-paginate
